driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: test-static-ip-centos
    image: generic/oracle8
    config_options:
      synced_folder: false
      cachier: false
    provider_raw_config_args:
      - 'qemu_use_session = true'
      - 'driver = "qemu"'
