# role tasks
- name: Set platform/version specific variables
  include_vars: "{{ __rolename_vars_file }}"
  loop:
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- become: "{{ k3s_worker_become }}"
  become_user: "{{ k3s_worker_become_user }}"
  block:
    - name: Install k3s on this node
      shell: >-
        /tmp/install-k3s.sh
        --server {{ k3s_worker_server }}
        --node-name {{ k3s_worker_node_name }}
        --token {{ k3s_worker_token }}
        {% for label in k3s_worker_node_labels %}
        --node-label {{ label }}
        {% endfor %}
      args:
        creates: /usr/local/bin/k3s
