- name: load vars
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
      path: "{{ role_path }}/vars"

- name: uncomment baseurl lines
  replace:
    path: /etc/yum.repos.d/{{ item }}.repo
    mode: preserve
    regexp: '^#baseurl=http://download.example/(.*)$'
    replace: baseurl=http://download.fedoraproject.org/\1
  loop: "{{ fedora_download_repos }}"

- name: comment out metalink lines
  replace:
    path: /etc/yum.repos.d/{{ item }}.repo
    mode: preserve
    regexp: '^metalink=(.*)$'
    replace: '#metalink=\1'
  loop: "{{ fedora_download_repos }}"
