galaxy_info:
  author: Greg Hellings
  description: Converts /etc/yum.repo.d/* files to use baseurl, not metalink
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis

dependencies: []
