galaxy_info:
  author: devroles
  description: |-
    Configures an rsync script to mirror down content to the local system
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all

dependencies: []
