galaxy_info:
  author: devroles
  description: |-
    Fixes a few basic inconsistencies in low-level Fedora machines, such as
    updating the base vim package (it's had issues in the past), and disabling
    SELinux on workstations
  license: GPLv3
  min_ansible_version: "2.8"
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all

dependencies: []
