driver:
  name: vagrant
  cachier: false
  provider:
    name: libvirt
platforms:
  - name: mariadb-fedora
    box: generic/fedora36
    config_options:
      synced_folder: false
    provider_raw_config_args:
      - 'qemu_use_session = true'
      - 'driver = "qemu"'
