# Use this test when you need to interact with system
# devices, systemd, services, etc
#
# The advantage of these boxes is that we can run the
# tests for this code up in GitHub Actions
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: test-packages_server
    # The set of "generic" boxes on Vagrant Hub has a
    # very robust set of distros available, including RHEL
    # if we need it. But generally the Oracle Linux is the
    # best successor to what CentOS used to be
    box: generic/oracle8
    config_options:
      synced_folder: false
      cachier: false
