# role tasks
- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ __rolename_vars_file }}"
  loop:
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- name: Prepare services and packages to k3s
  become: "{{ k3s_base_become }}"
  become_user: "{{ k3s_base_become_user }}"
  block:
    - name: Disable necessarily bad services
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - firewalld
        - nm-cloud-setup.service
        - nm-cloud-setup.timer
      ignore_errors: true  # noqa ignore-errors

    - name: Install prereqs
      ansible.builtin.package:
        name: "{{ k3s_base_packages }}"
        state: present
        disable_gpg_check: true

    - name: Fetch the install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: &script /tmp/install-k3s.sh
        owner: root
        group: root
        mode: "0755"
