dependency:
  options:
    role-file: ../requirements.yml  # relative to the role dir
    requirements-file: ../requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
lint: ''
platforms:
  - name: instance
    box: generic/fedora36
    config_options:
      synced_folder: false
      cachier: false
    provider_raw_config_args:
      - 'qemu_use_session = true'
      - 'driver = "qemu"'
    groups:
      - admin
      - sudo
      - private
      - gui
      - dev
      - cli
provisioner:
  playbooks:
    converge: ../../workstation.yml
