- name: ensure that sudo is installed
  become: "{{ sudoers_become }}"
  become_user: "{{ sudoers_become_user }}"
  package:
    name: "{{ sudoers_packages }}"
    state: present

- name: make sure include line is in file
  become: "{{ sudoers_become }}"
  become_user: "{{ sudoers_become_user }}"
  lineinfile:
    line: "#includedir /etc/sudoers.d"
    path: /etc/sudoers
    create: false

- name: be sure that /etc/sudoers.d exists
  become: "{{ sudoers_become }}"
  become_user: "{{ sudoers_become_user }}"
  file:
    path: /etc/sudoers.d
    state: directory
    owner: root
    group: root
    mode: 0750

- name: configure sudoers
  become: "{{ sudoers_become }}"
  become_user: "{{ sudoers_become_user }}"
  template:
    src: "{{ item }}"
    dest: /etc/sudoers.d/
    owner: root
    group: root
    mode: 0600
  with_items:
    - sudoers
    - sudoers_no_password
    - groups
    - groups_no_password
