galaxy_info:
  author: devroles
  description: Installs mythtv, particularly for Hauppage 950 cards
  license: GPLv3
  min_ansible_version: "2.4"
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
