- become: true
  block:
    - name: install packages elsewhere
      ansible.builtin.package:
        name: "{{ packages_workstation_libvirt }}"
        state: present
        use: "{{ packages_backend }}"

    - name: create image storage
      ansible.builtin.file:
        dest: "{{ packages_workstation_libvirt_storage }}"
        owner: root
        group: root
        mode: 0711
        state: directory

    - name: configure libvirt storage
      ansible.builtin.template:
        src: storage
        dest: /etc/libvirt/storage/default.xml
        owner: root
        group: root
        mode: 0755
      check_mode: true
      register: check

    - name: create libvirt config directory
      ansible.builtin.file:
        dest: /etc/libvirt/storage
        owner: root
        group: root
        mode: 0755
        state: directory
      when: check is changed  # noqa no-handler

    - name: make sure libvirt is stopped
      ansible.builtin.service:
        name: libvirtd
        state: stopped
      when:
        - check is changed  # noqa no-handler
        - ansible_connection not in ['docker', 'podman']

    - name: configure libvirt storage
      ansible.builtin.template:
        src: storage
        dest: /etc/libvirt/storage/default.xml
        owner: root
        group: root
        mode: 0755

    - name: ensure the libvirt group exists
      ansible.builtin.group:
        name: libvirt
        state: present

    - name: check for /usr/lib/group existence
      ansible.builtin.stat:
        path: /usr/lib/group
      register: group_file

    - when: group_file.stat.exists
      block:
        - name: fix issue with some versions of virt-manager messing up groups
          ansible.builtin.command: grep -E '^libvirt:' /usr/lib/group
          register: libvirt_group_line
          changed_when: false

        - name: ensure group is in /etc/group
          ansible.builtin.lineinfile:
            line: "{{ libvirt_group_line.stdout.strip() }}"
            path: /etc/group
            state: present

    - name: add current user to libvirt group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        append: true
        groups: libvirt

    - name: start and enable libvirtd
      ansible.builtin.service:
        name: libvirtd
        state: started
        enabled: true
      when: ansible_connection not in ['docker', 'podman']
      changed_when: false  # This is needed just to satisfy idempotence
