- name: disable tmpfs for /tmp to make Packer space
  become: true
  ansible.posix.systemd:
    masked: true
    state: stopped
    enabled: false
    name: tmp.mount
  failed_when: false
  when:
    - ansible_facts.service_mgr == 'systemd'
    - ansible_connection not in ['docker', 'podman']
