- name: Install flatpaks
  become: true
  community.general.flatpak:
    name: "{{ item }}"
  loop: "{{ packages_workstation_flatpaks }}"
  changed_when: false
  when: ansible_facts.hostname != 'toolbox'
