- name: Determine package backend
  ansible.builtin.set_fact:
    packages_backend: >-
      {{ (ansible_facts.pkg_mgr == 'atomic_container') |
      ternary('community.general.rpm_ostree_pkg', ansible_facts.pkg_mgr) }}

- name: install CLI repos and packages
  ansible.builtin.include_tasks: 01_cli.yml
  when: ansible_facts.pkg_mgr != 'atomic_container'

- block:
    - name: setup user-space virtualenvs
      ansible.builtin.include_tasks: 02_virtualenv.yml

    - name: setup libvirt
      ansible.builtin.include_tasks: 03_libvirt.yml

    - name: setup packer
      ansible.builtin.include_tasks: 04_packer.yml
  when: "'WSLENV' not in ansible_facts.env"

- name: setup kerberos
  ansible.builtin.include_tasks: 05_kerberos.yml
  when: kerberos is defined
