- name: Determine package backend
  ansible.builtin.set_fact:
    packages_backend: >-
      {{ (ansible_facts.pkg_mgr == 'atomic_container') |
      ternary('community.general.rpm_ostree_pkg', ansible_facts.pkg_mgr) }}

- name: Install CLI repos and packages
  ansible.builtin.include_tasks: 01_cli.yml
  when: ansible_facts.pkg_mgr != 'atomic_container'

- name: Setup systems for Linux (not WSL2)
  when: "'WSLENV' not in ansible_facts.env"
  block:
    - name: Setup user-space virtualenvs
      ansible.builtin.include_tasks: 02_virtualenv.yml

    - name: Setup libvirt
      ansible.builtin.include_tasks: 03_libvirt.yml

    - name: Setup packer
      ansible.builtin.include_tasks: 04_packer.yml

- name: Setup kerberos
  ansible.builtin.include_tasks: 05_kerberos.yml
  when: kerberos is defined

- name: Setup blu-ray files
  ansible.builtin.include_tasks: 06_blu_ray.yml

- name: Install flatpaks
  ansible.builtin.include_tasks: 07_flatpaks.yml
  when: ansible_connection not in ['docker', 'podman']
