galaxy_info:
  author: devroles
  description: Hole punching and local port forwarding for firewalld service
  license: GPLv3
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - firewall
    - firewalld

dependencies: []
