- name: Install gpg keys
  become: true
  package:
    name: distribution-gpg-keys
    state: present

- name: setup repositories
  import_role:
    name: oasis_roles.system.system_repositories
  vars:
    system_repositories_configs: "{{ packages_repositories }}"
    system_repositories_rpm_keys: "{{ packages_gpg_keys }}"

- name: install RPM Fusion packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_rpm_fusion }}"

- name: install CLI packages
  become: true
  package:
    name: "{{ packages_packages }}"
    state: present
  retries: 3
  register: install_cli
  until: install_cli is success

- name: remove packages that shouldn't hang around
  become: true
  package:
    name: "{{ packages_remove_packages }}"
    state: absent

- name: install dnf tools
  become: true
  package:
    name: "{{ packages_dnf_packages }}"
    state: present
  when: ansible_pkg_mgr == 'dnf'
  retries: 3
  register: install_dnf_tools
  until: install_dnf_tools is success
