- name: install CLI repos and packages
  import_tasks: 01_cli.yml
  when: ansible_facts.pkg_mgr not in ['atomic_container']

- block:
    - name: setup user-space virtualenvs
      import_tasks: 02_virtualenv.yml

    - name: setup libvirt
      import_tasks: 03_libvirt.yml

    - name: setup packer
      import_tasks: 04_packer.yml
  when: "'WSLENV' not in ansible_facts.env"

- name: setup kerberos
  import_tasks: 05_kerberos.yml
  when: kerberos is defined
