- name: read vars for install
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{
      ansible_distribution_major_version }}.yml"
    - "vars/default-os.yml"

- name: install necessary packages
  become: true
  include: install.yml

- name: configure Jenkins
  become: true
  include: configure.yml

- name: startup Jenkins
  become: true
  systemd:
    name: jenkins
    state: started
    enabled: true
