- name: install dhcpd packages
  become: "{{ dhcpd_become }}"
  package:
    name: "{{ dhcpd_packages }}"
    state: present

- name: configure dhcp options
  become: "{{ dhcpd_become }}"
  template:
    src: "{{ dhcpd_provider }}_dhcp.conf"
    dest: "{{ dhcpd_config_dest }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart dhcpd

- name: start dhcpd
  become: "{{ dhcpd_become }}"
  service:
    name: "{{ dhcpd_provider }}"
    state: started
    enabled: true
