- name: install dhcpd packages
  become: true
  package:
    name: "{{ dhcpd_packages }}"
    state: present

- name: configure dhcpd.conf
  become: true
  template:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart dhcpd

- name: start dhcpd
  become: true
  service:
    name: dhcpd
    state: started
    enabled: true
