galaxy_info:
  author: devroles
  description: >-
    Installs a baseline of packages that are useful to me on server machines
  license: GPLv3
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Fedora
      versions:
        - all

dependencies: []
