driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: mythtv-default
    box: greg-hellings/fedora-33-x86_64
provisioner:
  inventory:
    host_vars:
      localhost:
        molecule_openstack_ci_ssh_user: fedora
