driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: mythtv-default
    box: generic/fedora33
    config_options:
      synced_folder: false
      cachier: false
    provider_raw_config_args:
      - 'qemu_use_session = true'
      - 'driver = "qemu"'
provisioner:
  inventory:
    host_vars:
      localhost:
        molecule_openstack_ci_ssh_user: fedora
