driver:
  name: vagrant
platforms:
  - name: mythtv_default
    box: greg-hellings/fedora-32-x86_64
provisioner:
  inventory:
    host_vars:
      localhost:
        molecule_openstack_ci_ssh_user: fedora
