driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: virtualenv-ansible-python-ubuntu
    box: generic/ubuntu2004
    config_options:
      synced_folder: false
      cache.synced_folder_opts: '{ type: :sshfs }'
