galaxy_info:
  author: devroles
  description: Install certificates using the update-ca-trust command
  license: GPLv3
  min_ansible_version: "2.4"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies: []
