- name: Set bashrc_role_path
  ansible.builtin.set_fact:
    dotfiles_role_path: "{{ role_path }}"

- name: Run files
  devroles.system.copy_or_link:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: "{{ item.force | default(false) }}"
  loop: "{{ dotfiles_shell_files }}"
  tags:
    - skip_ansible_lint

- name: Set executable file permissions
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.local/bin/"
    mode: a+x
    recurse: true
