- name: set bashrc_role_path
  set_fact:
    bashrc_role_path: "{{ role_path }}"

- name: run files
  copy_or_link:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: "{{ item.force }}"
  loop: "{{ dotfiles_shell_files }}"
  tags:
    - skip_ansible_lint

- name: set executable file permissions
  file:
    dest: "{{ ansible_user_dir }}/.local/bin/"
    mode: a+x
    recurse: true
