- name: Configure git
  community.general.ini_file:
    path: "{{ ansible_user_dir }}/.gitconfig"
    section: "{{ item.name.split('.', 1)[0] }}"
    option: "{{ item.name.split('.', 1)[1] }}"
    value: "{{ item.value }}"
    mode: u+rw
  with_items: "{{ dotfiles_git_config_values }}"
