- name: ensure vim directory is created
  file:
    dest: "{{ item }}"
    state: directory
    force: true
    mode: "0755"
  with_items:
    - "{{ ansible_user_dir }}/.vim"
    - "{{ ansible_user_dir }}/.vim/autoload"
    - "{{ ansible_user_dir }}/.vim/bundle"
    - "{{ ansible_user_dir }}/.vim/sessions"

- name: install files
  devroles.system.copy_or_link:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: "{{ role_path }}/files/vimrc"
      dest: "{{ ansible_user_dir }}/.vimrc"
    - src: "{{ role_path }}/files/ftplugin"
      dest: "{{ ansible_user_dir }}/.vim/ftplugin"
  tags:
    - skip_ansible_lint

- name: download pathogen
  get_url:
    # yamllint disable-line rule:line-length
    url: https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest: "{{ ansible_user_dir }}/.vim/autoload"
    force: true

- name: checkout vim plugins
  git:
    dest: "{{ ansible_user_dir }}/.vim/bundle/{{ item.name }}"
    repo: "{{ item.repo }}"
    update: true
    version: master
  register: _dotfiles_vim_plugin
  retries: 2
  until: _dotfiles_vim_plugin is success
  loop: "{{ dotfiles_vim_plugins }}"
