- name: Setup shell config files
  ansible.builtin.include_tasks: 01_shell.yml

- name: Configure git
  ansible.builtin.include_tasks: 02_git.yml

- name: Configure vim
  ansible.builtin.include_tasks: 03_vim.yml

- name: Configure vagrant
  ansible.builtin.include_tasks: 04_vagrant.yml
