driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: packages-workstation
    box: generic/fedora35
    config_options:
      synced_folder: false
      cachier: false
    provider_raw_config_args:
      - 'qemu_use_session = true'
      - 'driver = "qemu"'
