galaxy_info:
  author: Greg Hellings
  description: >-
    Installs and configures a mail agent (MTA) on the target host
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
        - 8

dependencies: []
