- include_tasks: ensure_up.yml

- name: get certificate authorities
  include_tasks: update_center_certificates.yml

- name: install plugins
  include_tasks: install_plugins.yml

- include_tasks: ensure_up.yml
  vars:
    _jenkins_allow_api_key_failure: true

- name: configre
  include_tasks: configure.yml
