- name: create cert path
  file:
    dest: "{{ jenkins_home }}/update-center-rootCAs"
    state: directory
    owner: jenkins
    group: jenkins

- name: get certificates
  become: true
  become_user: "{{ jenkins_user }}"
  shell: >-
    set -e -o pipefail; openssl s_client -showcerts -connect
    {{ item.url | urlsplit("hostname") }}:443
    < /dev/null 2>/dev/null |
    openssl x509 -outform PEM > {{ item.url | urlsplit("hostname") }}.pem
  args:
    chdir: "{{ jenkins_home }}/update-center-rootCAs"
    creates: >-
      {{ jenkins_home }}/update-center-rootCAs/{{
      item.url | urlsplit('hostname') }}.pem
  loop: "{{ jenkins_configure_update_centers }}"
  when: item.url.startswith('https')
  notify: restart Jenkins
