driver:
  name: vagrant
platforms:
  - name: jenkins_configure_with_sec
    image: centos:8
    box: greg-hellings/centos-8-x86_64
    privileged: true
    command: /usr/lib/systemd/systemd --system
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  inventory:
    group_vars:
      all:
        jenkins_configure_security_enabled: true
