driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: test-toolbox
    box: generic/fedora34
    config_options:
      synced_folder: false
      cachier: false
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
