- name: generate public SSH key
  shell: >-
    ssh-keygen -y -f "{{ jenkins_user_home }}/.ssh/id_rsa" >
    "{{ jenkins_user_home }}/.ssh/id_rsa.pub"
  become: true
  become_user: "{{ jenkins_user }}"

- name: restart Jenkins
  service:
    name: jenkins
    state: restarted
  become: true
