galaxy_info:
  author: devroles
  description: |-
    Installs Java and basic things needed before installing Jenkins masters
    or Swarm clients
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all

dependencies: []
