# role tasks
- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ __rolename_vars_file }}"
  loop:
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- become: "{{ k3s_master_become }}"
  become_user: "{{ k3s_master_become_user }}"
  block:
    - name: Execute installer
      ansible.builtin.command: >-
        /tmp/install-k3s.sh
        --node-name {{ k3s_master_node_name }}
        {% if k3s_master_cluster_cidr %}
        --cluster-cidr {{ k3s_master_cluster_cidr }}
        {% endif %}
        {% if k3s_master_service_cidr %}
        --service-cidr {{ k3s_master_service_cidr }}
        {% endif %}
        {% if k3s_master_cluster_dns %}
        --cluster-dns {{ k3s_master_cluster_dns }}
        {% endif %}
      args:
        creates: /usr/local/bin/k3s

    - name: Start and enable the service
      ansible.builtin.service:
        name: k3s
        state: started
        enabled: true

    - name: Fetch k3s file
      ansible.builtin.fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: &kubeconfig "{{ inventory_dir }}/files/kube_config"
        flat: true
