# Basic
jenkins_user: jenkins
jenkins_home: /var/lib/jenkins
jenkins_master_version: "2.204.2"
jenkins_master_session_timeout: 480
jenkins_master_heap_size: 3g
jenkins_master_http_listen_address: ''
jenkins_master_https_listen_address: ''

# Advanced
jenkins_master_debug_level: 5
jenkins_master_enable_access_log: "no"
jenkins_master_handler_max: 100
jenkins_master_handler_idle: 20
jenkins_master_args: ''
jenkins_master_java_extra_options: []
jenkins_master_upgrade: false
jenkins_master_block_upgrade: false
jenkins_master_ajp_port: 8009
jenkins_master_ajp_listen_address: ''

# Super advanced
jenkins_master_rpm: jenkins-{{ jenkins_master_version }}-1.1
jenkins_master_java_cmd: /usr/bin/java
jenkins_master_soft_nofile_ulimit: 4096
jenkins_master_hard_nofile_ulimit: 4096
jenkins_master_soft_nproc_ulimit: 4096
jenkins_master_hard_nproc_ulimit: 30654
jenkins_master_fsize_ulimit: "{{ ansible_memtotal_mb * 1024 }}"
