galaxy_info:
  author: devroles
  description: |-
    Make sure that sudo is installed on the system and the
    given list of users are provided with appropriate levels
    of access
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: MacOS
      versions:
        - all

dependencies: []
