- when: ansible_facts.hostname != 'toolbox'
  become: true
  block:
    - name: ensure flatpak is present on the system
      ansible.builtin.package:
        name: flatpak
        state: present
      when: ansible_facts.pkg_mgr != 'atomic_container'

    - name: configure flatpak repos
      community.general.flatpak_remote:
        name: "{{ item.name }}"
        state: present
        flatpakrepo_url: "{{ item.url }}"
      loop: "{{ flatpak_repos }}"
