- name: ensure flatpak is present on the system
  become: true
  package:
    name: flatpak
    state: present
  when: ansible_facts.pkg_mgr not in ['atomic_container']

- name: configure flatpak repos
  become: true
  flatpak_remote:
    name: "{{ item.name }}"
    state: present
    flatpakrepo_url: "{{ item.url }}"
  loop: "{{ flatpak_repos }}"
