- when: ansible_facts.hostname != 'toolbox'
  block:
    - name: ensure flatpak is present on the system
      become: true
      package:
        name: flatpak
        state: present

    - name: configure flatpak repos
      become: true
      flatpak_remote:
        name: "{{ item.name }}"
        state: present
        flatpakrepo_url: "{{ item.url }}"
      loop: "{{ flatpak_repos }}"
