- name: include variable files
  ansible.builtin.include_vars: "{{ item }}"
  loop:
    - "{{ role_path }}/vars/{{ ansible_facts.architecture }}.yml"
  when: item is file

- name: include os files
  ansible.builtin.include_vars: "{{ item }}"
  loop:
    - "{{ role_path }}/vars/{{ ansible_facts.distribution }}.yml"
  when: item is file

- name: include files for our system
  ansible.builtin.include_tasks: "{{ ansible_facts.system }}/main.yml"
