- name: install tools
  become: true
  ansible.builtin.package:
    name: "{{ mirror_packages }}"
    state: present
  when: ansible_facts.pkg_mgr != 'unknown'

- name: make each mirror exist
  ansible.builtin.include_tasks: mirror.yml
  loop: "{{ mirror_list }}"

- name: setup SELinux
  ansible.builtin.include_tasks: selinux.yml
  when: ansible_facts.selinux.status in ['enforcing', 'permissive']
