- name: install tools
  become: true
  package:
    name: "{{ mirror_packages }}"
    state: present

- name: make each mirror exist
  include_tasks: mirror.yml
  loop: "{{ mirror_list }}"

- name: setup SELinux
  include_tasks: selinux.yml
  when: ansible_selinux.status in ['enforcing', 'permissive']
