- block:
    - name: create base dir
      file:
        dest: "{{ item.dest }}"
        state: directory
        owner: "{{ item.owner | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
        mode: "{{ item.mode | default('0755') }}"

    - name: create mirror.sh file
      copy:
        content: |
          #!/bin/bash
          set -ex
          excludes="$(mktemp)"
          cat > "${excludes}" << EOF
          {% for exclude in (item.excludes | default([])) %}
          {{ exclude }}
          {% endfor %}
          EOF
          flock -n "{{ item.dest }}" rsync -avSHP --delete --exclude-from="${excludes}" \
              "{{ item.src }}" \
              "{{ item.dest }}" | tee "{{ mirror_log_dir }}/{{ item.name }}.log
          rm -f "${excludes}"
        dest: "{{ item.script_home }}/{{ item.name }}.sh"
        owner: "{{ item.owner | default(omit) }}"
        group: "{{ item.group | default(omit) }}"
        mode: "0755"
  become: "{{ mirror_become }}"
  become_user: "{{ mirror_become_user }}"
