- name: Give rsync access to the things
  become: true
  ansible.posix.seboolean:
    name: "{{ item }}"
    persistent: true
    state: true
  loop:
    - rsync_export_all_ro
    - rsync_client
    - rsync_full_access
