- name: set default conf path value
  set_fact:
    _config_path: false

- name: set conf path for dnf
  set_fact:
    _config_path: /etc/dnf/dnf.conf
  when: ansible_pkg_mgr == 'dnf'

- name: set conf path for yum
  set_fact:
    _config_path: /etc/yum.conf
  when: ansible_pkg_mgr == 'yum'

- name: update config
  community.general.ini_file:
    path: "{{ _config_path }}"
    section: main
    option: deltarpm
    value: "False"
    create: false
    allow_no_value: true
  when:
    - _config_path is string
    - (_config_path | length) != 0
  become: true
