# role tasks
- name: Set platform/version specific variables
  include_vars: "{{ __rolename_vars_file }}"
  loop:
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- name: Include provider information
  include_vars: "{{ __provider_vars_file }}"
  loop:
    - "{{ adblock_provider }}.yml"
  vars:
    __provider_vars_file: "{{ role_path }}/vars/{{ item }}"

- become: "{{ adblock_become }}"
  become_user: "{{ adblock_become_user }}"
  block:
    - name: Pull image
      containers.podman.podman_image:
        name: "{{ adblock_image }}"
        state: present
      notify: Restart container

    - name: Be sure group exists
      group:
        name: "{{ adblock_group }}"
        state: present

    - name: Be sure the user exists
      user:
        name: "{{ adblock_user }}"
        groups: "{{ adblock_group }}"
        state: present
        system: true

    - name: Create folders
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ adblock_user }}"
        group: "{{ adblock_group }}"
        mode: "0755"
        setype: container_file_t
      loop: "{{ adblock_paths }}"

    - name: Run service
      containers.podman.podman_container:
        name: "{{ adblock_container }}"
        image: "{{ adblock_image }}"
        volume: "{{ adblock_volumes }}"
        restart_policy: on-failure
        publish: "{{ adblock_ports }}"
        state: present

    - name: Create podman service file
      template:
        src: adblock-container.service
        dest: "/usr/lib/systemd/system/{{ adblock_provider }}-container.service"
        owner: root
        group: root
        mode: "0644"

    - name: Start and enable service
      service:
        name: "{{ adblock_provider }}-container"
        state: started
        enabled: true
