- name: check root password is defined
  ansible.builtin.assert:
    that: mariadb_admin_password is defined
    msg: You must provide an admin password for install

- name: load distro vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_facts.distribution }}-{{ ansible_facts.distribution_version }}.yml"
    - "vars/{{ ansible_facts.distribution }}-{{
          ansible_facts.distribution_major_version }}.yml"
    - "vars/{{ ansible_facts.distribution }}.yml"
    - "vars/generic.yml"

- name: Install EPEL
  ansible.builtin.include_role:
    name: epel

- name: install database
  become: true
  ansible.builtin.package:
    name: "{{ mariadb_packages }}"
    state: present
  register: __mariadb_install
  retries: 3
  until: __mariadb_install is success

- name: setup mysql data structures for first run
  become: true
  ansible.builtin.command: /usr/libexec/{{ mariadb_setup_dir_command }}
  args:
    creates: /var/lib/mysql/mysql
  register: _first_run
  ignore_errors: true

- name: start database
  become: true
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  when:
    - ansible_connection not in ['docker', 'podman']

- name: start database standalone
  become: true
  ansible.builtin.command: mysqld_safe --nowatch
  args:
    creates: /var/run/mariadb/mariadb.pid
  when:
    - ansible_connection in ['docker', 'podman']

- name: secure system on first boot
  ansible.builtin.include_tasks:
    file: secure.yml
  when: _first_run is changed

- name: configure MariaDB access
  ansible.builtin.include_tasks:
    file: configure_access.yml
