- name: Secure the installation with user permissions
  become: true
  block:
    - name: Remove anonymous users
      community.mysql.mysql_user:
        check_implicit_admin: true
        name: ""
        host_all: true
        state: absent
        login_unix_socket: "{{ mariadb_unix_socket | default(omit) }}"

    - name: Remove test database
      community.mysql.mysql_db:
        check_implicit_admin: true
        name: test
        state: absent
        login_unix_socket: "{{ mariadb_unix_socket | default(omit) }}"

    - name: Create admin for localhost only
      community.mysql.mysql_user:
        check_implicit_admin: true
        name: "{{ mariadb_admin_user }}"
        host: "{{ item }}"
        state: present
        login_unix_socket: "{{ mariadb_unix_socket | default(omit) }}"
      with_items: "{{ mariadb_admin_hosts }}"

    - name: Remove root user, if not admin
      community.mysql.mysql_user:
        check_implicit_admin: true
        name: root
        host_all: true
        state: absent
        login_unix_socket: "{{ mariadb_unix_socket | default(omit) }}"
      when: mariadb_admin_user != 'root'
