dhcpd_become: >-
  {{ (ansible_connection in ['docker','podman']) | ternary(False, True) }}
# No defaults:
# dhcpd_domain
dhcpd_lease_time: "1h"
# Define each element as
# - netmask: 255.255.255.0
#   start: 10.0.1.10
#   end: 10.0.1.177
#   routers:
#     - 10.0.0.1
#     - 10.0.0.2
#   options:
#     option-name: "some_value"
dhcpd_subnets: []
# Host entries look like this:
# - mac: 11:22:33:44:55:66
#   ip: "10.42.1.2"
# or
# - name: foo
# For the latter type, then any host that claims the
# name given will have its value drawn from the DNS
# hosts association
dhcpd_hosts: []
