dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: disable_deltarpm
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: testinfra
  lint:
    name: flake8
