driver:
  name: podman
lint: ''
platforms:
  - name: instance
    image: fedora:latest
    pre_build_image: true
provisioner:
  playbooks:
    converge: ../../dotfiles.yml
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
