- hosts: all
  tasks:
    - name: Install necessary testing tools
      become: true
      package:
        name:
          - git
        state: present
      retries: 3
      register: _install_tools
      until: _install_tools is success
