galaxy_info:
  author: Greg Hellings
  description: |-
    Configures .vim and .vimrc the way Greg likes it
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all

dependencies: []
