galaxy_info:
  author: Greg Hellings
  description: Create a molecule instance in Vagrant
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis

dependencies: []
