# e.g. this should be something like "fedora-toolbox:33"
toolbox_base_image: >-
  registry.fedoraproject.org/{{ ansible_facts.distribution | lower }}-toolbox:{{
  ansible_facts.distribution_version }}
