- name: setup the python executable correctly
  hosts: admin
  roles:
    - devroles.system.python_prep

- name: most baseline things
  hosts: admin
  roles:
    - role: oasis_roles.system.system_repositories
      system_repositories_configs: "{{ repositories }}"
      when: repositories is defined
    - devroles.system.common
    - devroles.system.mounts
    - oasis_roles.system.update_ca_trust
