- name: Configure desktop systems
  hosts: all
  roles:
    - role: devroles.system.flatpak
      when:
        - ansible_facts.distribution != 'MacOSX'
        - ansible_facts.pkg_mgr != 'atomic_container'
        - ansible_connection not in ['docker', 'podman']
    - role: devroles.system.container
      when:
        - ansible_connection not in ['docker', 'podman']
        - "'WSLENV' not in ansible_facts.env"

- name: Install packages to non-atomic stations
  hosts: all
  tasks:
    - when: ansible_facts.pkg_mgr != 'atomic_container'  # noqa unnamed-task
      ansible.builtin.include_role:
        name: "{{ role }}"
      loop:
        - devroles.system.packages_workstation
        - devroles.system.dev
      loop_control:
        loop_var: role
