- name: configure desktop systems
  hosts: all
  roles:
    - role: devroles.system.flatpak
      when:
        - ansible_facts.distribution != 'MacOSX'
    - role: devroles.system.flatpaks
      when:
        - ansible_facts.distribution != 'MacOSX'
    - devroles.system.packages_workstation
    - devroles.system.dev
    - oasis_roles.system.container
    - devroles.devel.ansible
    - devroles.devel.java_devel
    - devroles.devel.packaging
    - devroles.devel.sword
