- name: Install basic packages
  hosts: all
  roles:
    - devroles.system.packages_server

- name: Configure firewall
  hosts: admin
  roles:
    - role: devroles.system.firewalld
      when:
        - ansible_pkg_mgr not in ['atomic_container']
        - "'WSLENV' not in ansible_facts.env"
        - ansible_distribution != 'MacOSX'

- name: Configure mariadb/mysql database
  hosts: mariadb
  roles:
    - devroles.system.mariadb

- name: Configure webserver
  hosts: webserver
  roles:
    - devroles.system.webserver

- name: Configure mythtv
  hosts: mythtv
  roles:
    - devroles.system.mythtv

- name: Prepare k3s nodes
  hosts: k3s
  roles:
    - devroles.system.k3s_base

- name: Configure k3s
  hosts: k3s_master
  roles:
    - devroles.system.k3s_master

- name: Configure k3s workers
  hosts: k3s_workers
  roles:
    - devroles.system.k3s_worker

- name: Configure mirror
  hosts: mirrors
  roles:
    - role: devroles.system.mirror
