- name: load variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{
      ansible_distribution_major_version }}.yml"
    - "vars/default.yml"

- name: install java and other necessary packages
  become: true
  package:
    name: "{{ jenkins_packages }}"
    state: present
  retries: 2
  register: install_deps
  until: install_deps is success

- name: ensure SSH directory exists
  become: true
  file:
    name: "{{ jenkins_user_home }}/.ssh"
    owner: "{{ jenkins_user }}"
    group: jenkins
    mode: 0700
    state: directory

- name: ensure user has SSH key for Jenkins CLI usage
  command: >-
    ssh-keygen -b 4096 -t rsa -f {{ jenkins_user_home }}/.ssh/id_rsa -N ''
  args:
    creates: "{{ jenkins_user_home }}/.ssh/id_rsa"
  become: true
  become_user: "{{ jenkins_user }}"
  notify: generate public SSH key

- meta: flush_handlers

- name: read SSH key
  become: true
  slurp:
    src: "{{ jenkins_user_home }}/.ssh/id_rsa.pub"
  register: _id_rsa_pub

- name: add ssh keys to authorized_keys for the jenkins user
  become: true
  authorized_key:
    user: "{{ jenkins_user }}"
    state: present
    key: "{{ _id_rsa_pub['content'] | b64decode }}"
