- name: load variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{
      ansible_distribution_major_version }}.yml"
    - "vars/default.yml"

- name: install java and other necessary packages
  become: true
  package:
    name: "{{ jenkins_packages }}"
    state: present
  retries: 2
  register: install_deps
  until: install_deps is success

- name: Create the jenkins group
  become: true
  ansible.builtin.group:
    name: "{{ jenkins_user }}"
    state: present

- name: Create the jenkins user and key
  become: true
  ansible.builtin.user:
    name : "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    home : "{{ jenkins_home }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    state: present
  register: jenkins_user_object

- name: add ssh keys to authorized_keys for the jenkins user
  become: true
  authorized_key:
    user : "{{ jenkins_user }}"
    state: present
    key  : "{{ jenkins_user_object.ssh_public_key }}"
