galaxy_info:
  author: devroles
  description: Setups up a node to be a k3s master
  license: GPLv3
  min_ansible_version: "2.8"
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
