galaxy_info:
  author: devroles
  description: |-
    Configures an already-running Jenkins master
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all

dependencies: []
