galaxy_info:
  author: devroles
  description: Installs the flatpaks I want on my system
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis

dependencies: []
