driver:
  name: podman
platforms:
  - name: dns_server
    ## Remove 'image' above and uncomment the following to run systemd in Docker
    image: centos/systemd
    privileged: true
    command: /usr/lib/systemd/systemd --system
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
