- name: extract Hauppage firmware
  command: unzip -o -j HVR-950.zip Driver85/hcw85bda.sys
  args:
    chdir: "{{ ansible_user_dir }}"
    warn: false
  notify: run extract
  tags:
    - skip_ansible_lint

- name: run extract
  find:
    path: /usr/src/kernels
    recurse: false
    file_type: directory
  register: kernels
  notify: extract source
  failed_when: (kernels.files | length) == 0
  changed_when: true

- name: extract source
  command: "{{ kernels.files[0].path }}/scripts/extract_xc3028.pl"
  args:
    chdir: "{{ ansible_user_dir }}"
    creates: "{{ ansible_user_dir }}/xc3028-v27.fw"
  notify: move firmware

- name: move firmware
  become: true
  command: mv {{ ansible_user_dir }}/xc3028-v27.fw /lib/firmware
