galaxy_info:
  author: devroles
  description: >-
    Ensures that mount points exist on the system and that they are mounted and
    recorded in /etc/fstab
  license: GPLv3
  min_ansible_version: "2.4"
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all

dependencies: []
