- name: install necessary Ansible tools
  hosts: all
  tasks:
    - name: install necessary tools
      package:
        name:
          - iproute
          - dbus
          - NetworkManager
        state: present
      become: true

    - name: start dbus
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      become: true
      with_items:
        - dbus
        - NetworkManager
