jenkins_configure_cli_jar: >-
  {{ jenkins_cli_shell_user_home }}/jenkins-cli.jar
jenkins_configure_cli_jar_src: /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar
# Used to connect the CLI
jenkins_configure_url: >-
  http://{{ jenkins_configure_host }}{{ ':' +
  ( jenkins_configure_listening_port | string )
  if jenkins_configure_listening_port is defined else '' }}

jenkins_configure_user_api_retries: 3
#
# The default access roles that all Jenkins masters should have. Permissions are
# listed according to their Java name, and users/groups/etc that should have
# access to that role are lisetd in the "sids" array. In addition to this, every
# master will have an "admin" role created that has knowledge of every
# permission availble at the role's creation time. To add new roles or to
# override that admin role, use the jenkins_security_extra_roles variable in the
# defaults folder of this Ansible role
jenkins_configure_security_roles:
  - name: anonymous
    permissions:
      - com.synopsys.arc.jenkins.plugins.ownership.OwnershipPlugin.Jobs
      - hudson.model.Hudson.Read
      - hudson.model.View.Read
    sids:
      - anonymous
