driver:
  name: vagrant
platforms:
  - name: test_static_ip_fedora
    image: generic/fedora33
    config_options:
      synced_folder: false
      cachier: false
    provider_raw_config_args:
      - 'qemu_use_session = true'
      - 'driver = "qemu"'
