galaxy_info:
  author: Greg Hellings
  description: Manage the creation and destruction of container resources
    for running molecule in a container runtime environment backed by
    Podman
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: Fedora
      versions:
        - all
    - name: CentOS
      versions:
        - all
    - name: RHEL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - molecule

dependencies: []
