- name: converge
  hosts: all
  roles:
    - role: devroles.system.virtualenv_ansible_python
      virtualenv_ansible_python_packages:
        - dnszone
    - role: dns_server
      dns_server_domains:
        fiddlesticks.com:
          - name: '@'
            type: A
            value: 127.0.0.1
