# role tasks
- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ __rolename_vars_file }}"
  loop:
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- name: Install packages for servers
  become: true
  ansible.builtin.package:
    name: "{{ packages_server_packages }}"
    state: present
  retries: 3
  register: __packages_server_install
  until: __packages_server_install is success

- name: Create python virtualenvs
  ansible.builtin.pip:
    virtualenv: "{{ ansible_user_dir }}/venv/tools{{ item }}"
    state: present
    name: "{{ packages_server_python_packages }}"
    virtualenv_python: "python{{ item }}"
    virtualenv_site_packages: true
  loop:
    - "3"
  retries: 3
  register: __create_virtualenvs
  until: __create_virtualenvs is success
