driver:
  name: vagrant
  cachier: none
  provider:
    name: libvirt
platforms:
  - name: mariadb-vagrant
    box: generic/oracle8
    config_options:
      synced_folder: false
    provider_raw_config_args:
      - 'qemu_use_session = true'
      - 'driver = "qemu"'
provisioner:
  inventory:
    group_vars:
      all:
        ansible_connection: ssh
