- name: install CLI repos and packages
  include_tasks: 01_cli.yml
  when: ansible_facts.pkg_mgr not in ['atomic_container']

- block:
    - name: setup user-space virtualenvs
      include_tasks: 02_virtualenv.yml

    - name: setup libvirt
      include_tasks: 03_libvirt.yml
      when:
        - ansible_facts.architecture != 'aarch64'
        - ansible_connection not in ['podman', 'docker']

    - name: setup packer
      include_tasks: 04_packer.yml
      when: ansible_facts.architecture != 'aarch64'
  when: "'WSLENV' not in ansible_facts.env"

- name: setup kerberos
  include_tasks: 05_kerberos.yml
  when: kerberos is defined
