- name: Setup webserver
  ansible.builtin.import_role:
    name: webserver
  vars:
    webserver_domains:
      - mail.{{ item }}
  with_items: "{{ mta_domains }}"

- name: Install mta software
  become: true
  ansible.builtin.package:
    name: "{{ mta_packages }}"
    state: present
