- name: converge
  hosts: all
  roles:
    - role: devroles.system.copy_or_link
      copy_or_link_files:
        - src: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY')
                }}/../shared/first"
          dest: "{{ ansible_user_dir }}/first"
          force: false
        - src: "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY')
                }}/../shared/second"
          dest: "{{ ansible_user_dir }}/second"
          force: true
