- when: ansible_facts.pkg_mgr not in ['atomic_container']
  become: true
  block:
    - name: update selected packages
      ansible.builtin.package:
        name:
          - vim-minimal
        state: latest
      retries: 3
      register: update_selected
      until: update_selected is success
      tags:
        - skip_ansible_lint

    - name: install shared tools
      ansible.builtin.package:
        name: "{{ common_packages }}"
        state: present
      retries: 3
      register: shared_tools
      until: shared_tools is success

    - name: install dnf tools
      ansible.builtin.package:
        name:
          - dnf-command(system-upgrade)
        state: present
      when: ansible_facts.pkg_mgr == 'dnf'
      retries: 3
      register: install_dnf_tools
      until: install_dnf_tools is success

    - when:
        - ansible_facts.os_family != 'Darwin'
        - ansible_connection not in ['docker', 'podman']
      block:
        - name: install python SELinux packages
          ansible.builtin.package:
            name: "{{ common_selinux_packages }}"
            state: present

- name: disable selinux
  become: true
  ansible.builtin.selinux: state=disabled
  when:
    - ansible_facts.os_family != 'Darwin'
    - ansible_connection not in ['docker', 'podman']
    - ansible_facts.distribution not in ('CentOS', 'RHEL')

- name: enable SSHD
  become: true
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
  when:
    - ansible_facts.os_family != 'Darwin'
    - ansible_connection not in ['docker', 'podman']
    - "'WSLENV' not in ansible_facts.env"
