- name: set python package versions
  set_fact:
    _short_version: "{{ ansible_python.version.major }}"
    _long_version: >-
      {{ ansible_python.version.major
      }}.{{ ansible_python.version.minor }}

- name: install python{{ _short_version }}-dnf
  become: true
  shell: "{{ ansible_facts._pkg_mgr }} install -y python{{ _short_version }}-dnf"
  args:
    creates: >-
      /usr/lib/python{{ _long_version }}/site-packages/{{ ansible_facts._pkg_mgr }}
  tags:
    - skip_ansible_lint
  when: ansible_facts.pkg_mgr not in ['atomic_container']
