galaxy_info:
  author: devroles
  description: >-
    Installs and configures bind/named to serve names on the local network
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - all

dependencies: []
