- name: create mariadb
  hosts: all
  roles:
    - devroles.system.disable_deltarpm
    - devroles.system.mariadb
    - devroles.system.packages_server
  vars:
    mariadb_user_privs:
      - username: user
        password: &password p4ssw0rd!
        database: "*"
        privs: "ALL"
    mariadb_admin_password: *password
