- name: Ensure that the path exists
  ansible.builtin.file:
    path: "{{ item.dest | dirname }}"
    state: directory
    mode: u+wx
  loop: "{{ copy_or_link_files }}"

- name: Insert file
  devroles.system.copy_or_link:
  args: "{{ item }}"
  loop: "{{ copy_or_link_files }}"
  tags:
    - skip_ansible_lint  # TODO: Needs ansible-lint#642 resolved
