- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ __rolename_vars_file }}"
  loop:
    - default.yml
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- name: Install certs
  become: "{{ update_ca_trust_become }}"
  become_user: "{{ update_ca_trust_become_user }}"
  block:
    - name: Install certs from URLs
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: "{{ update_ca_trust_anchors }}"
        owner: root
        group: root
        mode: 0644
        validate_certs: "{{ update_ca_trust_validate_certs }}"
      with_items: "{{ update_ca_trust_urls }}"
      notify: update-ca-trust

    - name: Install certs from files
      ansible.builtin.copy:
        content: "{{ lookup(update_ca_trust_template | bool | ternary('template', 'file'), item) }}\n"  # noqa template-instead-of-copy
        dest: "{{ update_ca_trust_anchors }}/{{ item | basename }}"
        owner: root
        group: root
        mode: 0644
      with_items: "{{ update_ca_trust_files }}"
      notify: update-ca-trust

- name: Run handlers if necessary
  ansible.builtin.meta: flush_handlers
