galaxy_info:
  author: devroles
  description: Installs yum/dnf repositories and their keys
  license: GPLv3
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 5
        - 6
        - 7
        - 8
    - name: Fedora
      versions:
        - all

  galaxy_tags:
    - repositories
    - yum
    - dnf

dependencies: []
