galaxy_info:
  author: devroles
  description: Sets a static IP address for NetworkManager connections
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - all

dependencies: []
