- name: converge
  hosts: all
  roles:
    - role: mounts
  vars:
    mounts:
      - mount_point: /mnt/defaults
        device: /dev/vdb1
        fstype: ext4
      - mount_point: /mnt/cloud-user
        device: /dev/vdc1
        fstype: ext4
        owner: cloud-user
      - mount_point: /mnt/restricted-access
        device: /dev/vdd1
        fstype: ext4
        mode: "0700"
