driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: mariadb-vagrant
    box: generic/oracle8
    config_options:
      synced_folder: false
      cache.synced_folder_opts: '{ type: :sshfs }'
provisioner:
  inventory:
    group_vars:
      all:
        ansible_connection: ssh
