- name: converge
  hosts: all
  roles:
    - role: dhcpd
      dhcpd_authoritative: true
      dhcpd_subnets:
        - address: "{{ ansible_default_ipv4.network }}"
          netmask: "{{ ansible_default_ipv4.netmask }}"
          start: "{{ ansible_default_ipv4.network }}"
          end: >-
            {{ (ansible_default_ipv4.network.split('.'))[:3] |
                join('.') }}.255
          routers:
            - "{{ ansible_default_ipv4.gateway }}"
