- name: install necesssary tools
  hosts: all
  tasks:
    - name: install iproute - without it, Ansible won't probe IP info
      become: "{{ ansible_connection not in ['docker', 'podman'] }}"
      package:
        name: iproute
        state: present
