- name: install necesssary tools
  hosts: all
  tasks:
    - name: install iproute - without it, Ansible won't probe IP info
      become: true
      package:
        name: iproute
        state: present
