- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ __rolename_vars_file }}"
  loop:
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- name: Install necessary devel packages
  become: "{{ ansible_facts.distribution != 'MacOSX' }}"
  ansible.builtin.package:
    name: "{{ dev_packages }}"
    state: present
  when: ansible_facts.pkg_mgr not in ['atomic_container']

- name: Install development flatpaks
  become: true
  community.general.packaging.os.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ dev_paks }}"
  when:
    - ansible_facts.hostname != 'toolbox'
    - ansible_facts.distribution != 'MacOSX'
    - ansible_connection not in ['docker', 'podman']

- name: Configure user for mock
  become: true
  ansible.builtin.user:
    groups: mock
    name: "{{ dev_mock_user }}"
    append: true

- name: Create .m2 directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.m2/"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: "0755"

- name: Populate Maven settings file
  ansible.builtin.template:
    src: settings.xml
    dest: "{{ ansible_user_dir }}/.m2/settings.xml"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
