- name: Set platform/version specific variables
  include_vars: "{{ __rolename_vars_file }}"
  loop:
    - "{{ ansible_facts.os_family }}.yml"
    - "{{ ansible_facts.distribution }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_major_version }}.yml"
    - "{{ ansible_facts.distribution }}_{{ ansible_facts.distribution_version }}.yml"
  vars:
    __rolename_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __rolename_vars_file is file

- name: install necessary devel packages
  become: "{{ ansible_facts.distribution != 'MacOSX' }}"
  package:
    name: "{{ dev_packages }}"
    state: present
  when: ansible_facts.pkg_mgr not in ['atomic_container']

- name: install development boxen
  become: true
  flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ dev_paks }}"
  when:
    - ansible_facts.hostname != 'toolbox'
    - ansible_facts.distribution != 'MacOSX'
