# This has to come first, before anything else gets executed, as the nodes
# that it creates get added to the inventory and configured following this
- name: configure toolboxes
  hosts: cli
  roles:
    - role: devroles.system.toolbox
      when:
        - ansible_facts.pkg_mgr == 'atomic_container'
        - ansible_facts.architecture not in ['aarch64']

- name: setup the python executable correctly
  hosts: admin
  roles:
    - devroles.system.python_prep

- name: most baseline things
  hosts: admin
  roles:
    - role: oasis_roles.system.system_repositories
      system_repositories_configs: "{{ repositories }}"
      when: repositories is defined
    - devroles.system.common
    - devroles.system.mounts
    - oasis_roles.system.update_ca_trust
