- hosts: localhost
  tasks:
    - name: Configure repositories
      action: community.kubernetes.helm_repository
      args: "{{ item }}"
      loop:
        - repo_name: ingress-nginx
          repo_url: https://kubernetes.github.io/ingress-nginx
        - repo_name: kubernetes-dashboard
          repo_url: https://kubernetes.github.io/dashboard/
        - repo_name: halkeye
          repo_url: https://halkeye.github.io/helm-charts/

    - name: Configure charts
      action: community.kubernetes.helm
      args: "{{ item }}"
      loop:
        - name: ingress-nginx
          chart_ref: ingress-nginx/ingress-nginx
          namespace: ingress-controller
          create_namespace: true
          values:
            kind: DaemonSet
