- name: configure firewall
  hosts: all
  roles:
    - role: oasis_roles.system.firewalld
      when: ansible_pkg_mgr not in ['atomic_container']

- name: configure mariadb/mysql database
  hosts: mariadb
  roles:
    - devroles.system.mariadb

- name: configure webserver
  hosts: webserver
  roles:
    - devroles.system.webserver

- name: configure mythtv
  hosts: mythtv
  roles:
    - devroles.system.mythtv
