- name: setup internal dns
  hosts: adblock
  roles:
    - role: oasis_roles.system.container
    - role: devroles.system.adblock

- name: configure firewall
  hosts: admin
  roles:
    - role: oasis_roles.system.firewalld
      when:
        - ansible_pkg_mgr not in ['atomic_container']
        - "'WSLENV' not in ansible_facts.env"

- name: configure mariadb/mysql database
  hosts: mariadb
  roles:
    - devroles.system.mariadb

- name: configure webserver
  hosts: webserver
  roles:
    - devroles.system.webserver

- name: configure mythtv
  hosts: mythtv
  roles:
    - devroles.system.mythtv
