- name: Configure sudo access
  hosts: sudo
  roles:
    - role: devroles.system.authorized_key
      when: inventory_hostname != 'localhost'
    - role: devroles.system.sudoers
      ansible_ssh_pipelining: false
