# From other places:
jenkins_home: /var/lib/jenkins
jenkins_user: jenkins
jenkins_cli_shell_user: "{{ ansible_user_id }}"
jenkins_cli_shell_user_home: "{{ ansible_user_dir }}"
jenkins_configure_envvars:
  - key: JENKINS_MASTER_URL
    value: "{{ jenkins_configure_url }}"


jenkins_configure_security_enabled: false
jenkins_configure_admin:
  name: admin
  email: root@localhost
  password: changeme
jenkins_configure_admin_sids: []
jenkins_configure_cli_users: []
jenkins_configure_local_users: []
jenkins_configure_security_extra_roles: []

jenkins_slave_agent_port: 50000
jenkins_configure_update_centers:
  - id: default
    #url: "https://updates.jenkins-ci.org/update-center.json"  # SSL errors?
    url: "https://mirror.xmission.com/jenkins/updates/update-center.json"
jenkins_configure_plugins:
  ansible:
  blueocean:
  blueocean-config:
  blueocean-dashboard:
  blueocean-git-pipeline:
  blueocean-github-pipeline:
  blueocean-personalization:
  blueocean-pipeline-editor:
  blueocean-pipeline-scm-api:
  blueocean-rest:
  blueocean-web:
  bouncycastle-api:
  build-blocker-plugin:
  command-launcher:
  copyartifact:
  credentials:
  delivery-pipeline-plugin:
  display-url-api:
  docker-build-step:
  docker-plugin:
  docker-slaves:
  docker-workflow:
  git-client:
  git-parameter:
  git:
  github-api:
  github-branch-source:
  github-organization-folder:
  github:
  #gitlab-hook:  # see note on ruby-runtime
  gitlab-merge-request-jenkins:
  gitlab-plugin:
  groovy:
  groovy-postbuild:
  ircbot:
  javadoc:
  jenkins-multijob-plugin:
  jms-messaging:
  junit:
  linenumbers:
  mailer:
  matrix-auth:
  matrix-project:
  Matrix-sorter-plugin:
  multiple-scms:
  nodelabelparameter:
  pam-auth:
  parameterized-trigger:
  pipeline-build-step:
  pipeline-github-lib:
  pipeline-graph-analysis:
  pipeline-input-step:
  pipeline-maven:
  pipeline-milestone-step:
  pipeline-model-api:
  pipeline-model-declarative-agent:
  pipeline-model-definition:
  pipeline-model-extensions:
  pipeline-rest-api:
  pipeline-stage-step:
  pipeline-stage-tags-metadata:
  pipeline-stage-view:
  pipeline-utility-steps:
  plain-credentials:
  postbuild-task:
  postbuildscript:
  preSCMbuildstep:
  project-build-times:
  project-description-setter:
  project-inheritance:
  publish-over-ssh:
  publish-over:
  pyenv-pipeline:
  python:
  rebuild:
  role-strategy:
  #ruby-runtime:  # needed for gitlab-hook, doesn't support Java 11
  saferestart:
  schedule-build:
  scm-api:
  scp:
  script-security:
  short-workspace-path:
  show-build-parameters:
  ssh-agent:
  ssh-credentials:
  ssh-slaves:
  subversion:
  swarm:
  windows-slaves:
  workflow-api:
  workflow-scm-step:
  workflow-step-api:
  ws-cleanup:

# LDAP plugin configuration values
#jenkins_configure_ldap:
#  server: ldaps://ldap.example.com
#  root_dn: dc=example,dc=com
#  user_search_base: ''
#  user_search: uid={0}
#  group_search_base: ou=groups
#  group_search_filter: "(& (cn={0}) (objectclass=posixGroup))"
#  group_membership: memberUid={1}
#  display_name_attr: displayname
#  email_addr_attr: mail
#  manager_dn: ''
#  manager_password: ''
