- name: create instances
  vagrant:
    # Primary options people will set
    instance_name: "{{ item.name }}"
    # Lets us possibly map from Docker to Vagrant when we need to
    platform_box: >-
      {{ item.box | default('greg-hellings/' +
      molecule_vagrant_ci_lookup[item.image | default('centos:8')]) }}
    provider_memory: "{{ item.memory | default(1024) }}"
    provider_cpus: "{{ item.cpus | default(2) }}"
    instance_interfaecs: "{{ item.interfaces | default(omit) }}"

    platform_box_version: "{{ item.box_version | default(omit) }}"
    platform_box_url: "{{ item.box_url | default(omit) }}"
    provider_name: "{{ molecule_vagrant_ci_provider }}"
    provider_options: "{{ item.provider_options | default(omit) }}"
    provider_raw_config_args: >-
      {{ item.provider_raw_config_args | default(omit) }}
    provider_override_args: "{{ item.provider_override_args | default(omit) }}"
    provision: "{{ item.provision | default(omit) }}"

    state: up
  register: _molecule_vagrant_ci_boxen
  loop: "{{ molecule_vagrant_ci_platforms }}"
  loop_control:
    label: "{{ item.name }}"

- block:
    - name: populate molecule configuration dict
      set_fact:
        _molecule_vagrant_ci_dict:
          instance: "{{ item.Host }}"
          address: "{{ item.HostName }}"
          user: "{{ item.User }}"
          port: "{{ item.Port }}"
          identity_file: "{{ item.IdentityFile }}"
      loop: "{{ _molecule_vagrant_ci_boxen.results }}"
      register: _molecule_vagrant_ci_config

    - name: convert to list
      set_fact:
        _molecule_podman_ci_instance_conf: >-
          {{ _molecule_vagrant_ci_config |
          map(attribute='ansible_facts._molecule_vagrant_ci_dict') | list }}

    - name: dump instance config
      copy:
        content: >-
          {{ _molecule_podman_ci_instance_conf | to_json |
          from_json | molecule_to_yaml | molecule_header }}
        dest: "{{ molecule_vagrant_ci_instance_config }}"
