- name: Install packages
  become: true
  ansible.builtin.package:
    name: "{{ mythtv_packages }}"
    state: present
  retries: 3
  register: install_packages
  until: install_packages is success

- name: Fetch Hauppage 950 firmware
  ansible.builtin.get_url:
    dest: "{{ ansible_user_dir }}/HVR-950.zip"
    url: "http://www.steventoth.net/linux/xc5000\
          /HVR-12x0-14x0-17x0_1_25_25271_WHQL.zip"
    force: true
    mode: 0644
  notify: extract Hauppage firmware

- name: Create mythtv database
  community.mysql.mysql_db:
    login_user: "{{ mythtv_db_admin_username | default(omit) }}"
    login_password: "{{ mythtv_db_admin_password | default(omit) }}"
    name: mythconverg
    state: present
    encoding: utf8

- name: Grant mythtv user privileges
  community.mysql.mysql_user:
    login_user: "{{ mythtv_db_admin_username | default(omit) }}"
    login_password: "{{ mythtv_db_admin_password | default(omit) }}"
    name: mythconverg
    priv: "mythconverg.*:ALL"
    state: present

- name: Give user permission to run capture card
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups:
      - video
    append: true
