galaxy_info:
  author: devroles
  description: Configures a basic DHCP server on CentOS
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
        - 8

dependencies: []
