galaxy_info:
  author: devroles
  description: Ensures that flatpak is installed on the host
  license: GPLv3
  min_ansible_version: "2.8"
  platforms:
    - name: EL
      versions:
        - "7"
    - name: Fedora
      versions:
        - all

dependencies: []
