- hosts: all
  vars:
    col_dir: "{{ molecule_scenario_directory }}/../../../../"
  tasks:
    - name: touch file
      file:
        state: touch
        dest: /root/second
        mode: 0600

    - name: install ansible
      package:
        name: ansible
        state: present

    - name: create play structure
      file:
        state: directory
        path: /root/temp
        owner: root
        group: root
        mode: 0644

    - name: create inventory file
      copy:
        content: "localhost ansible_connection=local"
        dest: /root/temp/inventory
        mode: 0644

    - name: create test files
      copy:
        src: "{{ item }}"
        dest: /root/temp/
        mode: 0644
      loop:
        - "{{ molecule_scenario_directory }}/../shared/first"
        - "{{ molecule_scenario_directory }}/../shared/second"
        - "{{ molecule_scenario_directory }}/remote_playbook.yml"

    - name: create archive of collection
      delegate_to: localhost
      archive:
        path: "{{ col_dir }}"
        dest: &archive "{{ col_dir }}/../my_collection.tar.gz"
        format: gz

    - name: create destination ansible_collections path
      file:
        path: &remote /root/temp/ansible_collections/devroles/system
        state: directory
        owner: root
        mode: 0755

    - name: unarchive collection
      unarchive:
        src: *archive
        dest: *remote
        list_files: true
