name: Test with Ansible

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request: {}
  schedule:
    - cron: '12 0 * * *'

env:
  TOX_ANSIBLE_DRIVER: docker
  ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/:~/work/
  checkout_path: ansible_collections/devroles/system

jobs:
  collect:
    runs-on: ubuntu-latest
    outputs:
      scenarios: ${{ steps.collection.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-modules
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          set -ex
          python -m pip install --upgrade pip
          pip install tox tox-ansible
      - name: collect depenencies
        id: collection
        run: |
          set -ex
          json="["
          for x in $(tox -l --ansible-driver docker); do
            json="${json}\"${x}\","
          done
          json="${json%,}]"
          echo "::set-output name=scenarios::${json}"

  build:
    needs: collect
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario: ${{ fromJson(needs.collect.outputs.scenarios) }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: ${{ env.checkout_path }}
      - name: update submodules
        run: |-
          set -ex
          cd "${{ env.checkout_path }}"
          git submodule update --remote --recursive
      - name: Setup pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-modules
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools
          pip install -U wheel
          pip install tox tox-ansible
      - name: Run tox against ${{ matrix.scenario }}
        run: |
          set -ex
          mv ansible_collections ~/work/
          cd ~/work/${{ env.checkout_path }}
          tox -e ${{ matrix.scenario }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: release!
        run: |
          ansible-galaxy collection build
          ansible-galaxy collection publish *.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}
      - name: Release artifacts to Git Hub
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./devroles-system*.tar.gz
          allowUpdates: true
          name: Rlease ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
