name: Test with Ansible

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request: {}
  schedule:
    - cron: '12 0 * * *'

env:
  TOX_ANSIBLE_DRIVER: docker
  ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/:~/work/
  COLLECTION: system
  COLLECTION_NAMESPACE: devroles

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role:
          - authorized_key
          - bashrc
          - cli
          - common
          - copy_or_link
          - dev
          - dhcpd
          - disable_deltarpm
          - gitconfig
          - gui
          - jenkins
          - jenkins_master
          - jenkins_configure
          - mariadb
          - mirror
          - python_prep
          - sudoers
          - virtualenv_ansible_python
          - vimrc
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --remote --recursive
      - name: Setup pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-modules
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-ansible
      - name: Test with tox
        run: |
          cd ..
          dest="${HOME}/work/ansible_collections/${COLLECTION_NAMESPACE}"
          mkdir -p "${dest}"
          mv "$(basename "${GITHUB_REPOSITORY}")" "${dest}/${COLLECTION}"
          # post actions fail if this doesn't exist
          mkdir -p "$(basename "${GITHUB_REPOSITORY}")"
          cd "${dest}/${COLLECTION}"
          tox --ansible-role ${{ matrix.role }}
