name: tox

"on":
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - AUTHORS
      - galaxy.yml
      - .github/labels.yml
      - .github/release-drafter.yml
      - .github/workflows/build_toolboxen.yml
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '12 0 * * *'
  release:
    types:
      - published
      - prereleased

jobs:
  build:
    uses: devroles/meta_test/.github/workflows/build.yml@main

  release:
    needs:
      - build
    if: github.event_name == 'release'
    uses: devroles/meta_test/.github/workflows/release.yml@main
    secrets:
      galaxy_api_key: "${{ secrets.GALAXY_API_KEY }}"
