name: tox

"on":
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - AUTHORS
      - galaxy.yml
      - .github/labels.yml
      - .github/release-drafter.yml
      - .github/workflows/build_toolboxen.yml
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '12 0 * * *'
  release:
    types:
      - published
      - prereleased

jobs:
  collect:
    runs-on: ubuntu-latest
    outputs:
      scenarios: ${{ steps.zipped.outputs.scenarios }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          set -ex
          python -m pip install --upgrade tox
      - name: Collect container tests
        id: collection
        uses: greg-hellings/tox-list@v1
        with:
          tox-args: --ansible-driver docker --ansible-driver podman --ansible-driver containers
      - name: Collect VM tests
        id: vagrant
        uses: greg-hellings/tox-list@v1
        with:
          tox-args: --ansible-driver vagrant
      - id: zipped
        name: Zip arrays together
        shell: python
        run: |
          import json
          ubuntu = json.loads('${{ steps.collection.outputs.tox-envs }}')
          macos  = json.loads('${{ steps.vagrant.outputs.tox-envs }}')
          ub_zip = [{'os': 'ubuntu-latest', 'scenario': u} for u in ubuntu]
          mac_zip = [{'os': 'macos-10.15', 'scenario': m} for m in macos]
          print("::set-output name=scenarios::" + json.dumps(ub_zip + mac_zip))

  build:
    needs:
      - collect
    uses: devroles/meta_test/.github/workflows/build.yml@master
    with:
      scenarios: "${{ needs.collect.outputs.scenarios }}"

  release:
    needs:
      - build
    if: github.event_name == 'release'
    uses: devroles/meta_test/.github/workflows/release.yml@master
    secrets:
      galaxy_api_key: "${{ secrets.GALAXY_API_KEY }}"
