name: Test with Ansible

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request: {}
  schedule:
    - cron: '12 0 * * *'

env:
  TOX_ANSIBLE_DRIVER: docker
  ANSIBLE_COLLECTIONS_PATHS: ~/.ansible/:~/work/
  COLLECTION: system
  COLLECTION_NAMESPACE: devroles

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        role:
          - authorized_key
          - bashrc
          - cli
          - common
          - copy_or_link
          - dev
          - dhcpd
          - disable_deltarpm
          - gitconfig
          - gui
          - jenkins
          - jenkins_master
          - jenkins_configure
          - mariadb
          - mirror
          - python_prep
          - sudoers
          - virtualenv_ansible_python
          - vimrc
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          path: ${{ github.workspace }}/ansible_collections/devroles/system
      - name: Setup pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-modules
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: "3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools
          pip install -U wheel
          pip install tox tox-ansible
      - name: Test with tox
        run: |
          set -e
          cd ansible_collections/devroles/system
          tox --ansible-role ${{ matrix.role }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: release!
        run: |
          ansible-galaxy collection build
          ansible-galaxy collection publish *.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}
      - name: Release artifacts to Git Hub
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./devroles-system*.tar.gz
          allowUpdates: true
          name: Rlease ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
