name: tox

"on":
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
      - AUTHORS
      - galaxy.yml
      - .github/labels.yml
      - .github/release-drafter.yml
      - .github/workflows/build_toolboxen.yml
  pull_request:
  schedule:
    - cron: '12 0 * * *'
  release:
    types:
      - published
      - prereleased

jobs:
  collect:
    runs-on: ubuntu-latest
    outputs:
      scenarios: ${{ steps.collection.outputs.tox-envs }}
      vagrant: ${{ steps.vagrant.outputs.tox-envs }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          set -ex
          python -m pip install --upgrade tox
      - name: Collect dependencies
        id: collection
        uses: greg-hellings/tox-list@v1
        with:
          tox-args: --ansible-driver docker --ansible-driver podman --ansible-driver containers
      - id: vagrant
        uses: greg-hellings/tox-list@v1
        with:
          tox-args: --ansible-driver vagrant

  lint:
    uses: devroles/meta_test/.github/workflows/lint.yml@master

  vagrant_build:
    needs:
      - collect
    uses: devroles/meta_test/.github/workflows/vagrant_build.yml@master
    with:
      scenarios: "${{ needs.collect.outputs.vagrant }}"

  build:
    needs:
      - collect
    uses: devroles/meta_test/.github/workflows/container_build.yml@master
    with:
      scenarios: "${{ needs.collect.outputs.scenarios }}"

  release:
    needs:
      - lint
      - build
      - vagrant_build
    if: github.event_name == 'release'
    uses: devroles/meta_test/.github/workflows/release.yml@master
    secrets:
      galaxy_api_key: "${{ secrets.GALAXY_API_KEY }}"
