- name: create blu-ray config directories
  file:
    dest: "{{ ansible_user_dir }}/.config/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - aacs

- name: download aacs files
  get_url:
    url: https://vlc-bluray.whoknowsmy.name/files/KEYDB.cfg
    dest: "{{ ansible_user_dir }}/.config/aacs"
    force: true
    validate_certs: false

#- name: download bdplus archive
#  get_url:
#    url: http://www.labdv.com/aacs/libbdplus/bdplus-vm0.bz2
#    dest: "{{ ansible_user_dir }}/.config
#    force: true
#
#- name: extract archive
#  shell: tar xaf bdplus-vm0.bz2
#  args:
#    creates: "{{ ansible_user_dir }}/.config/bdplus"
#    chdir: "{{ ansible_user_dir }}?.config
#
#- name: set ownership on files
#  file:
#    dest: "{{ item }}"
#    recurse: true
#    owner: "{{ ansible_user_id }}"
#  with_items:
#    - "{{ ansible_user_dir }}/.config/bdplus"
#    - "{{ ansible_user_dir }}/.config/aacs"
