- name: install CLI packages
  become: true
  package:
    name: "{{ cli_packages }}"
    state: present
  retries: 3
  register: install_cli
  until: install_cli is success

- name: remove packages that shouldn't hang around
  become: true
  package:
    name: "{{ cli_remove_packages }}"
    state: absent

- name: install dnf tools
  become: true
  package:
    name: "{{ cli_dnf_packages }}"
    state: present
  when: ansible_pkg_mgr == 'dnf'
  retries: 3
  register: install_dnf_tools
  until: install_dnf_tools is success
